//user
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const USER_REGISTER_START = 'USER_REGISTER_START';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR';
export const USER_LOGIN_START = 'USER_LOGIN_START';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const USER_INFO_START = 'USER_INFO_START';
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const USER_INFO_ERROR = 'USER_INFO_ERROR';
export const USER_LOG_OUT = 'USER_LOG_OUT';
export const HOME_INFO_START = 'HOME_INFO_START';
export const HOME_INFO_SUCCES = 'HOME_INFO_SUCCES';
export const HOME_INFO_ERROR = 'HOME_INFO_ERROR';
export const HOME_CREATE_START = 'HOME_CREATE_START';
export const HOME_CREATE_SUCCES = 'HOME_CREATE_SUCCES';
export const HOME_CREATE_ERROR = 'HOME_CREATE_ERROR';
export const HOME_SEND_REQUEST_START = 'HOME_SEND_REQUEST_START';
export const HOME_SEND_REQUEST_SUCCES = 'HOME_SEND_REQUEST_SUCCES';
export const HOME_SEND_REQUEST_ERROR = 'HOME_SEND_REQUEST_ERROR';
export const TASK_FETCH_ALL_FOR_USER_START = 'TASK_FETCH_ALL_FOR_USER_START';
export const TASK_FETCH_ALL_FOR_USER_SUCCES = 'TASK_FETCH_ALL_FOR_USER_SUCCES';
export const TASK_FETCH_ALL_FOR_USER_ERROR = 'TASK_FETCH_ALL_FOR_USER_ERROR';


